# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bienvenue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import cv2
import os

from subprocess import call
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtGui import QIcon


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(717, 405)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(320, 0, 81, 71))
        self.label_6.setStyleSheet("background-image: url(:/image/6.png);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/image/6.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 70, 621, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 120, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(280, 180, 51, 51))
        self.pushButton.setStyleSheet("image: url(:/image/ajouter.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 180, 51, 51))
        self.pushButton_2.setStyleSheet("image: url(:/image/camera.jpg);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(230, 260, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 240, 61, 21))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(0)
        self.label_2.setMidLineWidth(0)
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setIndent(-1)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(390, 240, 61, 21))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(0)
        self.label_3.setMidLineWidth(0)
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setIndent(-1)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 320, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(-10, 0, 731, 411))
        self.label_7.setStyleSheet("background-image: url(:/image/white.jpg);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/image/white.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Welcome"))
        self.label.setText(_translate("Form", "          Welcome to Our Application"))
        self.label_4.setText(
            _translate(
                "Form",
                "                     To start the diagnosis, you need to take or import an image.",
            )
        )
        self.label_5.setText(_translate("Form", "                To view appointments"))
        self.label_2.setText(_translate("Form", "     import"))
        self.label_3.setText(_translate("Form", "     take"))
        self.pushButton_3.setText(_translate("Form", "Appointments"))
        self.pushButton.clicked.connect(self.add)
        self.pushButton_2.clicked.connect(self.camera)

    def camera(self):
        cam = cv2.VideoCapture(0)
        thickness = 2
        num_circles = 1
        pt1 = (200, 200)
        pt2 = (450, 300)

        while True:
            re, img = cam.read()

            if not re:
                break
            center = (img.shape[1] // 2, img.shape[0] // 2)
            radius = img.shape[0] // 2
            for i in range(num_circles):
                r = (i + 1) * radius // num_circles
                cv2.circle(img, center, r, (0, 0, 255), thickness)
                cv2.rectangle(img, pt1, pt2, (0, 0, 255), thickness)
                cv2.imshow("test", img)
            k = cv2.waitKey(1)
            if k % 256 == 27:
                break
            elif k % 256 == 32:
                file = "D:/img.jpg"
                cv2.imwrite(file, img)
                cam.release
                cv2.destroyAllWindows()
                break
        cam.release
        cv2.destroyAllWindows

        model = tf.keras.models.load_model(
            "C:\\Users\\Hamza\\Downloads\\Projet_Leucocorie.zip\\Projet_Leucocorie_Khaled_Aziz_Hamza\\modele.h5"
        )

        img = image.load_img(file, target_size=(200, 200))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        images = np.vstack([x])
        val = model.predict(images)
        if val == 0:
            Form.destroy()
            call(
                [
                    "python",
                "C:/Users/Hamza/Downloads/Projet_Leucocorie.zip/Projet_Leucocorie_Khaled_Aziz_Hamza/malade.py",    ]                
            )
        else:
            Form.destroy()
            call(
                [
                    "python",
                    "C:/Users/Hamza/Downloads/Projet_Leucocorie.zip/Projet_Leucocorie_Khaled_Aziz_Hamza/saine.py",
                ]
            )

    def add(self):
        filename = QFileDialog.getOpenFileName()
        model = tf.keras.models.load_model(
                  "C:/Users/Hamza/Downloads/Projet_Leucocorie.zip/Projet_Leucocorie_Khaled_Aziz_Hamza/modele.h5"
        )
        dir_path = filename[0]
        img = image.load_img(dir_path, target_size=(200, 200))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        images = np.vstack([x])
        val = model.predict(images)
        if val == 0:
            Form.destroy()
            call(
                [
                    "python",
                    "C:/Users/Hamza/Downloads/Projet_Leucocorie.zip/Projet_Leucocorie_Khaled_Aziz_Hamza/malade.py",
                ]
            )
        else:
            Form.destroy()
            call(
                [
                    "python",
                    "C:/Users/Hamza/Downloads/Projet_Leucocorie.zip/Projet_Leucocorie_Khaled_Aziz_Hamza/saine.py",
                ]
            )

    def open_appointments(self):
        Form.destroy()
        call(
            [
                "python",
                "C://Users/asus/Desktop/projet/Projet_Leucocorie_Khaled_Aziz_Hamza/formulaire.py",
            ]
        )


import image_rc


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
