# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import mysql.connector
from PyQt5 import uic

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QDialog,
    QPushButton,
    QMessageBox,
    QVBoxLayout,
    QMainWindow,
    QApplication,
)
from subprocess import call


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(738, 410)
        Form.setFocusPolicy(QtCore.Qt.ClickFocus)

        Form.setStyleSheet("QWidget{\n" "border-radius: 20px ;\n" "}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 50, 461, 131))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(130, 200, 211, 41))
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setStyleSheet(
            "QLineEdit{\n"
            "    background-color: rgb(236, 236, 236);\n"
            "border-radius: 20px ;\n"
            "}"
        )
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 260, 211, 41))
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_3.setStyleSheet(
            "QLineEdit{\n"
            "    background-color: rgb(236, 236, 236);\n"
            "\n"
            "border-radius: 20px ;\n"
            "}"
        )
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(180, 320, 111, 41))
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "    color: rgb(0, 0, 0);\n"
            "border-radius: 20px ;\n"
            "background-image: url(:/image/2.png);\n"
            "}\n"
            ""
        )
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setAutoRepeatDelay(1000)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(470, -20, 291, 441))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(480, 130, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(480, 180, 231, 61))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 240, 111, 41))
        self.pushButton_3.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 20px ;\n"
            "    background-color: rgb(255, 255, 255);\n"
            "}"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(-10, 0, 481, 411))
        self.label_5.setStyleSheet("background-image: url(:/image/white.jpg);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/image/white.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(190, 0, 81, 71))
        self.label_6.setStyleSheet("background-image: url(:/image/6.png);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/image/6.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_5.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_3.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_3.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(
            _translate(
                "Form",
                '<html><head/><body><p align="center">Log in to your </p><p align="center">account</p></body></html>',
            )
        )
        self.lineEdit.setPlaceholderText(_translate("Form", "Email"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Sign in"))
        self.label_3.setText(_translate("Form", "     New here?"))
        self.label_4.setText(
            _translate(
                "Form",
                '<html><head/><body><p align="center">Sign up and get a </p><p align="center">good eye diagnosis</p></body></html>',
            )
        )
        self.pushButton_3.setText(_translate("Form", "Sign up"))
        self.pushButton_3.clicked.connect(self.Button_clicked)
        self.pushButton.clicked.connect(self.login)

    def connecting(self):
        try:
            self.mydb = mysql.connector.connect(
                host="localhost", user="root", passwd="", db="login"
            )
            self.mysqlcursor = self.mydb.cursor()
        except mysql.connector.errors.ProgrammingError as error:
            print("Review the Error -->", error)

    def login(self):
        self.connecting()
        user_name = self.lineEdit.text()
        password = self.lineEdit_3.text()
        if user_name == "" and password == "":
            QMessageBox.warning(None, "Login", "Fill in the data", QMessageBox.Ok)
        else:
            get_data = (user_name, password)
            query = "SELECT * FROM usuario WHERE email = %s and password = %s"
            self.mysqlcursor.execute(query, get_data)
            validate = self.mysqlcursor.fetchall()
            if validate:
                Form.destroy()
                call(
                    [
                        "python",
                        "C://Users/asus/Desktop/projet/Projet_Leucocorie_Khaled_Aziz_Hamza/bienvenue.py",
                    ]
                )
            else:
                QMessageBox.warning(
                    None,
                    "Login Incorrect",
                    "Incorrect user or password",
                    QMessageBox.Ok,
                )

    def Button_clicked(self):
        Form.destroy()
        call(
            [
                "python",
                "C://Users/asus/Desktop/projet/Projet_Leucocorie_Khaled_Aziz_Hamza/inscrire.py",
            ]
        )


import image_rc


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
